name: Update Badges

on:
  schedule:
    - cron: "0 2 * * *"
  workflow_dispatch:

jobs:
  update-badges:
    name: Update README with Credly Badges
    runs-on: ubuntu-latest
    
    # Force the runner to handle Node transitions smoothly
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    permissions:
      contents: write
      
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Fetch and Update Credly Badges
        uses: pemtajo/badge-readme@main
        with:
          CREDLY_USER: "sean-rhani-dela-cruz"
          NUMBER_LAST_BADGES: 10
